/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.51 from the
 * contents of XS.xs. Do not edit this file, edit XS.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "XS.xs"
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "bart.h"

/* Helpers: increment/decrement SV refcounts for values stored in the trie */

static void sv_val_dec(pTHX_ void *val) {
    if (val) SvREFCNT_dec((SV*)val);
}

/* Free all SV* values in a node tree (called before bart_table_free) */
static void free_node_svs(pTHX_ bart_node_t *node) {
    int i;
    if (!node) return;
    /* Free prefix SVs */
    for (i = 0; i < node->prefixes.len; i++) {
        sv_val_dec(aTHX_ node->prefixes.items[i]);
    }
    /* Free child SVs recursively */
    for (i = 0; i < node->children.len; i++) {
        void *tagged = node->children.items[i];
        int tag = ptr_tag(tagged);
        void *child = untag_ptr(tagged);
        switch (tag) {
            case NODE_BART:
                free_node_svs(aTHX_ (bart_node_t*)child);
                break;
            case NODE_LEAF:
                sv_val_dec(aTHX_ ((leaf_node_t*)child)->value);
                break;
            case NODE_FRINGE:
                sv_val_dec(aTHX_ ((fringe_node_t*)child)->value);
                break;
        }
    }
}

/* Parse "addr/len" or bare IP. Returns is_ipv6. */
static int parse_prefix_str(pTHX_ const char *str, uint8_t *addr, int *addr_len, int *prefix_len) {
    char buf[256];
    const char *slash;
    int is_ipv6;

    strncpy(buf, str, sizeof(buf) - 1);
    buf[sizeof(buf) - 1] = '\0';

    slash = strchr(buf, '/');
    if (slash) {
        buf[slash - buf] = '\0';
        *prefix_len = atoi(slash + 1);
    } else {
        *prefix_len = -1; /* will be set based on address type */
    }

    is_ipv6 = (strchr(buf, ':') != NULL);

    if (is_ipv6) {
        /* Parse IPv6 using inet_pton */
        struct in6_addr in6;
        if (inet_pton(AF_INET6, buf, &in6) != 1) {
            croak("Invalid IPv6 address: %s", buf);
        }
        memcpy(addr, &in6, 16);
        *addr_len = 16;
        if (*prefix_len < 0) *prefix_len = 128;
    } else {
        if (!parse_ipv4(buf, addr)) {
            croak("Invalid IPv4 address: %s", buf);
        }
        memset(addr + 4, 0, 12);
        *addr_len = 4;
        if (*prefix_len < 0) *prefix_len = 32;
    }

    mask_prefix(addr, *addr_len, *prefix_len);
    return is_ipv6;
}

/* Parse bare IP for lookup/contains. */
static int parse_ip_str(pTHX_ const char *str, uint8_t *addr) {
    int is_ipv6 = (strchr(str, ':') != NULL);
    if (is_ipv6) {
        struct in6_addr in6;
        if (inet_pton(AF_INET6, str, &in6) != 1) {
            croak("Invalid IPv6 address: %s", str);
        }
        memcpy(addr, &in6, 16);
    } else {
        if (!parse_ipv4(str, addr)) {
            croak("Invalid IPv4 address: %s", str);
        }
    }
    return is_ipv6;
}


#line 110 "XS.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 254 "XS.c"

XS_EUPXS(XS_Net__BART__XS_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Net__BART__XS_new)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "class");
    {
	const char *	class = (const char *)SvPV_nolen(ST(0))
;
	SV *	RETVAL;
#line 108 "XS.xs"
    bart_table_t *t = bart_table_new();
    SV *obj = newSViv(PTR2IV(t));
    SV *objref = newRV_noinc(obj);
    sv_bless(objref, gv_stashpv(class, GV_ADD));
    RETVAL = objref;
#line 272 "XS.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Net__BART__XS_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Net__BART__XS_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV *	self = ST(0)
;
#line 120 "XS.xs"
    bart_table_t *t = INT2PTR(bart_table_t*, SvIV(SvRV(self)));
    free_node_svs(aTHX_ t->root4);
    free_node_svs(aTHX_ t->root6);
    bart_table_free(t);
#line 294 "XS.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Net__BART__XS_insert); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Net__BART__XS_insert)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "self, prefix_str, value");
    {
	SV *	self = ST(0)
;
	const char *	prefix_str = (const char *)SvPV_nolen(ST(1))
;
	SV *	value = ST(2)
;
	int	RETVAL;
	dXSTARG;
#line 131 "XS.xs"
    bart_table_t *t = INT2PTR(bart_table_t*, SvIV(SvRV(self)));
    uint8_t addr[16];
    int addr_len, prefix_len;
    int is_ipv6 = parse_prefix_str(aTHX_ prefix_str, addr, &addr_len, &prefix_len);
    bart_node_t *root = is_ipv6 ? t->root6 : t->root4;

    SV *sv_copy = newSVsv(value);
    void *old_val = NULL;
    int is_new = bart_insert(root, addr, addr_len, prefix_len, 0, (void*)sv_copy, &old_val);

    if (!is_new && old_val) {
        SvREFCNT_dec((SV*)old_val);
    }
    if (is_new) {
        if (is_ipv6) t->size6++; else t->size4++;
    }
    RETVAL = is_new;
#line 333 "XS.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Net__BART__XS_lookup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Net__BART__XS_lookup)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, ip_str");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	self = ST(0)
;
	const char *	ip_str = (const char *)SvPV_nolen(ST(1))
;
#line 156 "XS.xs"
    bart_table_t *t = INT2PTR(bart_table_t*, SvIV(SvRV(self)));
    uint8_t addr[16];
    int is_ipv6 = parse_ip_str(aTHX_ ip_str, addr);
    int found = 0;
    void *val = bart_lookup(t, addr, is_ipv6, &found);
    if (found && val) {
        XPUSHs(sv_2mortal(newSVsv((SV*)val)));
        XPUSHs(sv_2mortal(newSViv(1)));
    } else {
        XPUSHs(&PL_sv_undef);
        XPUSHs(sv_2mortal(newSViv(0)));
    }
#line 367 "XS.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Net__BART__XS_contains); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Net__BART__XS_contains)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, ip_str");
    {
	SV *	self = ST(0)
;
	const char *	ip_str = (const char *)SvPV_nolen(ST(1))
;
	int	RETVAL;
	dXSTARG;
#line 174 "XS.xs"
    bart_table_t *t = INT2PTR(bart_table_t*, SvIV(SvRV(self)));
    uint8_t addr[16];
    int is_ipv6 = parse_ip_str(aTHX_ ip_str, addr);
    RETVAL = bart_contains(t, addr, is_ipv6);
#line 392 "XS.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Net__BART__XS_get); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Net__BART__XS_get)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, prefix_str");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	self = ST(0)
;
	const char *	prefix_str = (const char *)SvPV_nolen(ST(1))
;
#line 186 "XS.xs"
    bart_table_t *t = INT2PTR(bart_table_t*, SvIV(SvRV(self)));
    uint8_t addr[16];
    int addr_len, prefix_len;
    int is_ipv6 = parse_prefix_str(aTHX_ prefix_str, addr, &addr_len, &prefix_len);
    int found = 0;
    void *val = bart_get(t, addr, prefix_len, is_ipv6, &found);
    if (found && val) {
        XPUSHs(sv_2mortal(newSVsv((SV*)val)));
        XPUSHs(sv_2mortal(newSViv(1)));
    } else {
        XPUSHs(&PL_sv_undef);
        XPUSHs(sv_2mortal(newSViv(0)));
    }
#line 427 "XS.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Net__BART__XS_delete); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Net__BART__XS_delete)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, prefix_str");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	self = ST(0)
;
	const char *	prefix_str = (const char *)SvPV_nolen(ST(1))
;
#line 205 "XS.xs"
    bart_table_t *t = INT2PTR(bart_table_t*, SvIV(SvRV(self)));
    uint8_t addr[16];
    int addr_len, prefix_len;
    int is_ipv6 = parse_prefix_str(aTHX_ prefix_str, addr, &addr_len, &prefix_len);
    bart_node_t *root = is_ipv6 ? t->root6 : t->root4;
    int found = 0;
    void *val = bart_delete(root, addr, prefix_len, 0, &found);
    if (found) {
        if (is_ipv6) t->size6--; else t->size4--;
        if (val) {
            XPUSHs(sv_2mortal(newSVsv((SV*)val)));
            SvREFCNT_dec((SV*)val);
        } else {
            XPUSHs(&PL_sv_undef);
        }
        XPUSHs(sv_2mortal(newSViv(1)));
    } else {
        XPUSHs(&PL_sv_undef);
        XPUSHs(sv_2mortal(newSViv(0)));
    }
#line 468 "XS.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Net__BART__XS_size); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Net__BART__XS_size)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV *	self = ST(0)
;
	int	RETVAL;
	dXSTARG;
#line 230 "XS.xs"
    bart_table_t *t = INT2PTR(bart_table_t*, SvIV(SvRV(self)));
    RETVAL = t->size4 + t->size6;
#line 489 "XS.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Net__BART__XS_size4); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Net__BART__XS_size4)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV *	self = ST(0)
;
	int	RETVAL;
	dXSTARG;
#line 239 "XS.xs"
    bart_table_t *t = INT2PTR(bart_table_t*, SvIV(SvRV(self)));
    RETVAL = t->size4;
#line 511 "XS.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Net__BART__XS_size6); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Net__BART__XS_size6)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV *	self = ST(0)
;
	int	RETVAL;
	dXSTARG;
#line 248 "XS.xs"
    bart_table_t *t = INT2PTR(bart_table_t*, SvIV(SvRV(self)));
    RETVAL = t->size6;
#line 533 "XS.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C" {
#endif
XS_EXTERNAL(boot_Net__BART__XS); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Net__BART__XS)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if PERL_VERSION_LE(5, 8, 999) /* PERL_VERSION_LT is 5.33+ */
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("Net::BART::XS::new", XS_Net__BART__XS_new);
        newXS_deffile("Net::BART::XS::DESTROY", XS_Net__BART__XS_DESTROY);
        newXS_deffile("Net::BART::XS::insert", XS_Net__BART__XS_insert);
        newXS_deffile("Net::BART::XS::lookup", XS_Net__BART__XS_lookup);
        newXS_deffile("Net::BART::XS::contains", XS_Net__BART__XS_contains);
        newXS_deffile("Net::BART::XS::get", XS_Net__BART__XS_get);
        newXS_deffile("Net::BART::XS::delete", XS_Net__BART__XS_delete);
        newXS_deffile("Net::BART::XS::size", XS_Net__BART__XS_size);
        newXS_deffile("Net::BART::XS::size4", XS_Net__BART__XS_size4);
        newXS_deffile("Net::BART::XS::size6", XS_Net__BART__XS_size6);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

#ifdef __cplusplus
}
#endif
